# Generated by Django 5.0.6 on 2024-07-12 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_calendarevent_owner_alter_inventoryitem_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('annual_income', models.FloatField()),
                ('spending_score', models.FloatField()),
                ('demand', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
